"""Weekly CRM health report → markdown + Slack.

Usage:
    python tools/weekly_report.py --source mock --week 16 --post-slack
    python tools/weekly_report.py --source airtable --week 16 --no-llm

Output:
    runs/YYYY-WW-crm-health.md (markdown)
    Slack message via SLACK_WEBHOOK_URL (if --post-slack)
"""

import argparse
import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent.parent))

from shared.env_loader import load_env, get_optional
from shared.logger import info, error, warn
from shared.cost_tracker import check_budget, record_cost
from shared.sandbox import validate_write_path
from crm.factory import get_client


PROJECT_ROOT = Path(__file__).parent.parent


def _llm_narrative(stats: dict, source: str) -> str:
    """One-paragraph narrative for the report. Falls back to template if no LLM."""
    try:
        from openai import OpenAI
    except ImportError:
        return _template_narrative(stats, source)

    euri_key = get_optional("EURI_API_KEY")
    openrouter_key = get_optional("OPENROUTER_API_KEY")

    if euri_key:
        client = OpenAI(base_url="https://api.euron.one/api/v1/euri", api_key=euri_key)
        model = "gpt-4o-mini"
    elif openrouter_key:
        client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=openrouter_key)
        model = "openai/gpt-4o-mini"
    else:
        return _template_narrative(stats, source)

    prompt = (
        f"Write a single concise paragraph (4-5 sentences) summarizing this week's CRM health. "
        f"Use plain English, no marketing fluff, surface 1 specific insight or risk. "
        f"Stats (CRM={source}): {json.dumps(stats)}"
    )

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
            max_tokens=250,
        )
        record_cost("weekly_report_narrative", 0.002)
        return (response.choices[0].message.content or "").strip()
    except Exception as e:
        warn(f"LLM narrative failed: {e}")
        return _template_narrative(stats, source)


def _template_narrative(stats: dict, source: str) -> str:
    return (
        f"This week the {source} CRM saw {stats.get('new_leads', 0)} new leads, of which "
        f"{stats.get('scored', 0)} were scored. Distribution: {stats.get('hot', 0)} hot, "
        f"{stats.get('warm', 0)} warm, {stats.get('cold', 0)} cold. "
        f"{stats.get('contacted', 0)} have been contacted and {stats.get('qualified', 0)} qualified — "
        f"a {stats.get('conversion_rate_pct', 0)}% qualification rate."
    )


def _build_markdown(stats: dict, narrative: str, source: str, week: int, year: int) -> str:
    top_sources = "\n".join(f"- {s['source']}: {s['count']}" for s in stats.get("top_sources", [])) or "- (none)"
    return f"""# CRM Health Report — Week {week}, {year}

> **Source:** {source}
> **Generated:** {datetime.now(timezone.utc).isoformat()}

## Narrative

{narrative}

## Numbers

| Metric | Count |
|--------|-------|
| New leads | {stats.get('new_leads', 0)} |
| Scored | {stats.get('scored', 0)} |
| Hot | {stats.get('hot', 0)} |
| Warm | {stats.get('warm', 0)} |
| Cold | {stats.get('cold', 0)} |
| Contacted | {stats.get('contacted', 0)} |
| Qualified | {stats.get('qualified', 0)} |
| Qualification rate | {stats.get('conversion_rate_pct', 0)}% |

## Top sources

{top_sources}

---
*Auto-generated by CRM_Automation/tools/weekly_report.py*
"""


def _post_slack(webhook_url: str, source: str, week: int, narrative: str, stats: dict) -> dict:
    text = (
        f"*CRM Health — Week {week} ({source})*\n"
        f"{narrative}\n\n"
        f"New: {stats.get('new_leads', 0)} | "
        f"Hot: {stats.get('hot', 0)} | Warm: {stats.get('warm', 0)} | Cold: {stats.get('cold', 0)} | "
        f"Qualified: {stats.get('qualified', 0)} ({stats.get('conversion_rate_pct', 0)}%)"
    )
    try:
        r = requests.post(webhook_url, json={"text": text}, timeout=10)
        if not r.ok:
            return {"status": "error", "code": r.status_code, "body": r.text[:200]}
        return {"status": "posted"}
    except requests.RequestException as e:
        return {"status": "error", "message": str(e)}


def main():
    parser = argparse.ArgumentParser(description="Weekly CRM health report")
    parser.add_argument("--source", required=True, choices=["airtable", "hubspot", "zoho", "mock"])
    parser.add_argument("--week", type=int, default=None,
                        help="ISO week number (defaults to current)")
    parser.add_argument("--days", type=int, default=7, help="Look-back window in days")
    parser.add_argument("--no-llm", action="store_true", help="Skip LLM narrative, use template")
    parser.add_argument("--post-slack", action="store_true")
    args = parser.parse_args()

    load_env()

    now = datetime.now(timezone.utc)
    year, iso_week, _ = now.isocalendar()
    week = args.week or iso_week
    since = now - timedelta(days=args.days)

    try:
        client = get_client(args.source)
    except (EnvironmentError, ValueError) as e:
        error(f"CRM init failed: {e}")
        sys.exit(2)

    info(f"Pulling {args.source} stats since {since.isoformat()}")
    stats = client.get_health_stats(since)

    if args.no_llm:
        narrative = _template_narrative(stats, args.source)
    else:
        check_budget(estimated_cost=0.005)
        narrative = _llm_narrative(stats, args.source)

    md = _build_markdown(stats, narrative, args.source, week, year)
    out_path = validate_write_path(str(PROJECT_ROOT / "runs" / f"{year}-W{week:02d}-crm-health.md"))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md)
    info(f"Report written to {out_path}")

    slack_result = None
    if args.post_slack:
        webhook = get_optional("SLACK_WEBHOOK_URL")
        if not webhook:
            warn("SLACK_WEBHOOK_URL not set — skipping Slack post")
            slack_result = {"status": "skipped", "reason": "no webhook"}
        else:
            slack_result = _post_slack(webhook, args.source, week, narrative, stats)

    print(json.dumps({
        "status": "success",
        "source": args.source,
        "week": week,
        "year": year,
        "stats": stats,
        "report_path": str(out_path),
        "slack": slack_result,
    }))


if __name__ == "__main__":
    main()
